/*
 * Student Swagger
 *
 * Student Test Rest API using Swagger
 *
 * API version: 1.0.0
 * Contact: vijay.pandey1@globallogic.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"database/sql"
	"fmt"
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "./go"
	_ "github.com/denisenkom/go-mssqldb"
)

func main() {
	log.Printf("Server started")

	condb, errdb := sql.Open("mssql", "server=localhost;database=VijayDB;")
	if errdb != nil {
		fmt.Println(" Error open db:", errdb.Error())
	}

	var (
		sqlversion string
	)

	rows, err := condb.Query("select @@version")
	if err != nil {
		log.Fatal(err)
	}
	for rows.Next() {
		err := rows.Scan(&sqlversion)
		if err != nil {
			log.Fatal(err)
		}
		log.Println(sqlversion)
	}
	defer condb.Close()

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":1111", router))
}
